<?php $pageTitle=$pageTitle??'Discover Your Signature Scent';$isAdmin=defined('ADMIN_CONTEXT')&&ADMIN_CONTEXT; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?=e($pageTitle)?> | Falcon Perfumes</title><link rel="stylesheet" href="<?=e(url('css/style.css'))?>"><script src="<?=e(url('js/script.js'))?>" defer></script></head><body>
<div class="topbar"><?= $isAdmin?'FALCON PERFUMES / STORE MANAGEMENT':'FREE DELIVERY ON ORDERS OVER USD 50 · DISCOVER YOUR SIGNATURE SCENT'?></div>
<header class="site-header"><div class="container nav"><a class="brand" href="<?=e(url($isAdmin?'admin/index.php':'index.php'))?>"><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M24 4C18 14 6 18 4 20c6 0 12 2 20 8 8-6 14-8 20-8C38 18 30 14 24 4ZM24 28v16"/></svg><span>FALCON<small>PERFUMES</small></span></a><button type="button" class="menu-button outline" data-menu aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation">
<?php if($isAdmin): if(admin()):foreach(['index.php'=>'Overview','products.php'=>'Products','taxonomy.php'=>'Brands & categories','orders.php'=>'Orders','customers.php'=>'Customers','messages.php'=>'Messages','password.php'=>'Password'] as $navPath=>$label):?><a href="<?=e(url('admin/'.$navPath))?>"><?=e($label)?></a><?php endforeach;?><form action="<?=e(url('admin/logout.php'))?>" method="post"><?php csrf();?><button class="link">Sign out</button></form><?php endif;else:?>
<a href="<?=e(url('index.php'))?>">Home</a><a href="<?=e(url('new-arrivals.php'))?>">New Arrivals</a><a href="<?=e(url('brands.php'))?>">Brands</a><a href="<?=e(url('contact.php'))?>">Contact</a><a href="<?=e(url(user()?'dashboard.php':'auth/login.php'))?>"><?=user()?'My account':'Login'?></a><a class="cart-link" href="<?=e(url('cart.php'))?>">Bag <span><?=array_sum($_SESSION['cart']??[])?></span></a>
<?php endif;?></nav></div></header>
<?php if(!empty($_SESSION['flash'])):?><div class="container"><div class="alert" role="status"><?=e($_SESSION['flash'])?></div></div><?php unset($_SESSION['flash']);endif;?>
<main>
